// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/channels/yuanbaobot/proto/biz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumCLawMsgType int32

const (
	EnumCLawMsgType_CLAW_MSG_UNKNOWN EnumCLawMsgType = 0
	EnumCLawMsgType_CLAW_MSG_GROUP   EnumCLawMsgType = 1
	EnumCLawMsgType_CLAW_MSG_PRIVATE EnumCLawMsgType = 2
)

// Enum value maps for EnumCLawMsgType.
var (
	EnumCLawMsgType_name = map[int32]string{
		0: "CLAW_MSG_UNKNOWN",
		1: "CLAW_MSG_GROUP",
		2: "CLAW_MSG_PRIVATE",
	}
	EnumCLawMsgType_value = map[string]int32{
		"CLAW_MSG_UNKNOWN": 0,
		"CLAW_MSG_GROUP":   1,
		"CLAW_MSG_PRIVATE": 2,
	}
)

func (x EnumCLawMsgType) Enum() *EnumCLawMsgType {
	p := new(EnumCLawMsgType)
	*p = x
	return p
}

func (x EnumCLawMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumCLawMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[0].Descriptor()
}

func (EnumCLawMsgType) Type() protoreflect.EnumType {
	return &file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[0]
}

func (x EnumCLawMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumCLawMsgType.Descriptor instead.
func (EnumCLawMsgType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{0}
}

type EnumHeartbeat int32

const (
	EnumHeartbeat_HEARTBEAT_UNKNOWN EnumHeartbeat = 0
	EnumHeartbeat_HEARTBEAT_RUNNING EnumHeartbeat = 1
	EnumHeartbeat_HEARTBEAT_FINISH  EnumHeartbeat = 2
)

// Enum value maps for EnumHeartbeat.
var (
	EnumHeartbeat_name = map[int32]string{
		0: "HEARTBEAT_UNKNOWN",
		1: "HEARTBEAT_RUNNING",
		2: "HEARTBEAT_FINISH",
	}
	EnumHeartbeat_value = map[string]int32{
		"HEARTBEAT_UNKNOWN": 0,
		"HEARTBEAT_RUNNING": 1,
		"HEARTBEAT_FINISH":  2,
	}
)

func (x EnumHeartbeat) Enum() *EnumHeartbeat {
	p := new(EnumHeartbeat)
	*p = x
	return p
}

func (x EnumHeartbeat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumHeartbeat) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[1].Descriptor()
}

func (EnumHeartbeat) Type() protoreflect.EnumType {
	return &file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[1]
}

func (x EnumHeartbeat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumHeartbeat.Descriptor instead.
func (EnumHeartbeat) EnumDescriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{1}
}

type SyncInformationType int32

const (
	SyncInformationType_SYNC_INFORMATION_TYPE_UNSPECIFIED SyncInformationType = 0
	SyncInformationType_SYNC_INFORMATION_TYPE_COMMANDS    SyncInformationType = 1
)

// Enum value maps for SyncInformationType.
var (
	SyncInformationType_name = map[int32]string{
		0: "SYNC_INFORMATION_TYPE_UNSPECIFIED",
		1: "SYNC_INFORMATION_TYPE_COMMANDS",
	}
	SyncInformationType_value = map[string]int32{
		"SYNC_INFORMATION_TYPE_UNSPECIFIED": 0,
		"SYNC_INFORMATION_TYPE_COMMANDS":    1,
	}
)

func (x SyncInformationType) Enum() *SyncInformationType {
	p := new(SyncInformationType)
	*p = x
	return p
}

func (x SyncInformationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncInformationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[2].Descriptor()
}

func (SyncInformationType) Type() protoreflect.EnumType {
	return &file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes[2]
}

func (x SyncInformationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncInformationType.Descriptor instead.
func (SyncInformationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{2}
}

type ImMsgSeq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgSeq        uint64                 `protobuf:"varint,1,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImMsgSeq) Reset() {
	*x = ImMsgSeq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImMsgSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImMsgSeq) ProtoMessage() {}

func (x *ImMsgSeq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImMsgSeq.ProtoReflect.Descriptor instead.
func (*ImMsgSeq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{0}
}

func (x *ImMsgSeq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *ImMsgSeq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type ImImageInfoArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImImageInfoArray) Reset() {
	*x = ImImageInfoArray{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImImageInfoArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImImageInfoArray) ProtoMessage() {}

func (x *ImImageInfoArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImImageInfoArray.ProtoReflect.Descriptor instead.
func (*ImImageInfoArray) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{1}
}

func (x *ImImageInfoArray) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ImImageInfoArray) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImImageInfoArray) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImImageInfoArray) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImImageInfoArray) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MsgContent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ImageFormat    uint32                 `protobuf:"varint,3,opt,name=imageFormat,proto3" json:"imageFormat,omitempty"`
	Data           string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Desc           string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Ext            string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Sound          string                 `protobuf:"bytes,7,opt,name=sound,proto3" json:"sound,omitempty"`
	ImageInfoArray []*ImImageInfoArray    `protobuf:"bytes,8,rep,name=imageInfoArray,proto3" json:"imageInfoArray,omitempty"`
	Index          uint32                 `protobuf:"varint,9,opt,name=index,proto3" json:"index,omitempty"`
	Url            string                 `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`
	FileSize       uint32                 `protobuf:"varint,11,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileName       string                 `protobuf:"bytes,12,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgContent) Reset() {
	*x = MsgContent{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContent) ProtoMessage() {}

func (x *MsgContent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContent.ProtoReflect.Descriptor instead.
func (*MsgContent) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{2}
}

func (x *MsgContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MsgContent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MsgContent) GetImageFormat() uint32 {
	if x != nil {
		return x.ImageFormat
	}
	return 0
}

func (x *MsgContent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MsgContent) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MsgContent) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *MsgContent) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *MsgContent) GetImageInfoArray() []*ImImageInfoArray {
	if x != nil {
		return x.ImageInfoArray
	}
	return nil
}

func (x *MsgContent) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MsgContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MsgContent) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MsgContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type MsgBodyElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgContent    *MsgContent            `protobuf:"bytes,2,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBodyElement) Reset() {
	*x = MsgBodyElement{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBodyElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBodyElement) ProtoMessage() {}

func (x *MsgBodyElement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBodyElement.ProtoReflect.Descriptor instead.
func (*MsgBodyElement) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{3}
}

func (x *MsgBodyElement) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *MsgBodyElement) GetMsgContent() *MsgContent {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

type LogInfoExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInfoExt) Reset() {
	*x = LogInfoExt{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInfoExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInfoExt) ProtoMessage() {}

func (x *LogInfoExt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInfoExt.ProtoReflect.Descriptor instead.
func (*LogInfoExt) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{4}
}

func (x *LogInfoExt) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SendC2CMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	FromAccount   string                 `protobuf:"bytes,3,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	MsgRandom     uint32                 `protobuf:"varint,4,opt,name=msgRandom,proto3" json:"msgRandom,omitempty"`
	MsgBody       []*MsgBodyElement      `protobuf:"bytes,5,rep,name=msgBody,proto3" json:"msgBody,omitempty"`
	GroupCode     string                 `protobuf:"bytes,6,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	MsgSeq        uint64                 `protobuf:"varint,7,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
	LogExt        *LogInfoExt            `protobuf:"bytes,8,opt,name=logExt,proto3" json:"logExt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendC2CMessageReq) Reset() {
	*x = SendC2CMessageReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendC2CMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendC2CMessageReq) ProtoMessage() {}

func (x *SendC2CMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendC2CMessageReq.ProtoReflect.Descriptor instead.
func (*SendC2CMessageReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{5}
}

func (x *SendC2CMessageReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendC2CMessageReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendC2CMessageReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendC2CMessageReq) GetMsgRandom() uint32 {
	if x != nil {
		return x.MsgRandom
	}
	return 0
}

func (x *SendC2CMessageReq) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *SendC2CMessageReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendC2CMessageReq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *SendC2CMessageReq) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

type SendC2CMessageRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendC2CMessageRsp) Reset() {
	*x = SendC2CMessageRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendC2CMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendC2CMessageRsp) ProtoMessage() {}

func (x *SendC2CMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendC2CMessageRsp.ProtoReflect.Descriptor instead.
func (*SendC2CMessageRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{6}
}

func (x *SendC2CMessageRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendC2CMessageRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendGroupMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	GroupCode     string                 `protobuf:"bytes,2,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	FromAccount   string                 `protobuf:"bytes,3,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount     string                 `protobuf:"bytes,4,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	Random        string                 `protobuf:"bytes,5,opt,name=random,proto3" json:"random,omitempty"`
	MsgBody       []*MsgBodyElement      `protobuf:"bytes,6,rep,name=msgBody,proto3" json:"msgBody,omitempty"`
	RefMsgId      string                 `protobuf:"bytes,7,opt,name=refMsgId,proto3" json:"refMsgId,omitempty"`
	MsgSeq        uint64                 `protobuf:"varint,8,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
	LogExt        *LogInfoExt            `protobuf:"bytes,9,opt,name=logExt,proto3" json:"logExt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageReq) Reset() {
	*x = SendGroupMessageReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageReq) ProtoMessage() {}

func (x *SendGroupMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageReq.ProtoReflect.Descriptor instead.
func (*SendGroupMessageReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{7}
}

func (x *SendGroupMessageReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendGroupMessageReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendGroupMessageReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendGroupMessageReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendGroupMessageReq) GetRandom() string {
	if x != nil {
		return x.Random
	}
	return ""
}

func (x *SendGroupMessageReq) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *SendGroupMessageReq) GetRefMsgId() string {
	if x != nil {
		return x.RefMsgId
	}
	return ""
}

func (x *SendGroupMessageReq) GetMsgSeq() uint64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *SendGroupMessageReq) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

type SendGroupMessageRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageRsp) Reset() {
	*x = SendGroupMessageRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageRsp) ProtoMessage() {}

func (x *SendGroupMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageRsp.ProtoReflect.Descriptor instead.
func (*SendGroupMessageRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{8}
}

func (x *SendGroupMessageRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupMessageRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InboundMessagePush struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CallbackCommand      string                 `protobuf:"bytes,1,opt,name=callbackCommand,proto3" json:"callbackCommand,omitempty"`
	FromAccount          string                 `protobuf:"bytes,2,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount            string                 `protobuf:"bytes,3,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	SenderNickname       string                 `protobuf:"bytes,4,opt,name=senderNickname,proto3" json:"senderNickname,omitempty"`
	GroupId              string                 `protobuf:"bytes,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupCode            string                 `protobuf:"bytes,6,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	GroupName            string                 `protobuf:"bytes,7,opt,name=groupName,proto3" json:"groupName,omitempty"`
	MsgSeq               uint32                 `protobuf:"varint,8,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
	MsgRandom            uint32                 `protobuf:"varint,9,opt,name=msgRandom,proto3" json:"msgRandom,omitempty"`
	MsgTime              uint32                 `protobuf:"varint,10,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	MsgKey               string                 `protobuf:"bytes,11,opt,name=msgKey,proto3" json:"msgKey,omitempty"`
	MsgId                string                 `protobuf:"bytes,12,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgBody              []*MsgBodyElement      `protobuf:"bytes,13,rep,name=msgBody,proto3" json:"msgBody,omitempty"`
	CloudCustomData      string                 `protobuf:"bytes,14,opt,name=cloudCustomData,proto3" json:"cloudCustomData,omitempty"`
	EventTime            uint32                 `protobuf:"varint,15,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	BotOwnerId           string                 `protobuf:"bytes,16,opt,name=botOwnerId,proto3" json:"botOwnerId,omitempty"`
	RecallMsgSeqList     []*ImMsgSeq            `protobuf:"bytes,17,rep,name=recallMsgSeqList,proto3" json:"recallMsgSeqList,omitempty"`
	ClawMsgType          EnumCLawMsgType        `protobuf:"varint,18,opt,name=clawMsgType,proto3,enum=trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumCLawMsgType" json:"clawMsgType,omitempty"`
	PrivateFromGroupCode string                 `protobuf:"bytes,19,opt,name=privateFromGroupCode,proto3" json:"privateFromGroupCode,omitempty"`
	LogExt               *LogInfoExt            `protobuf:"bytes,20,opt,name=logExt,proto3" json:"logExt,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InboundMessagePush) Reset() {
	*x = InboundMessagePush{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessagePush) ProtoMessage() {}

func (x *InboundMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessagePush.ProtoReflect.Descriptor instead.
func (*InboundMessagePush) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{9}
}

func (x *InboundMessagePush) GetCallbackCommand() string {
	if x != nil {
		return x.CallbackCommand
	}
	return ""
}

func (x *InboundMessagePush) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *InboundMessagePush) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *InboundMessagePush) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *InboundMessagePush) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *InboundMessagePush) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *InboundMessagePush) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *InboundMessagePush) GetMsgSeq() uint32 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *InboundMessagePush) GetMsgRandom() uint32 {
	if x != nil {
		return x.MsgRandom
	}
	return 0
}

func (x *InboundMessagePush) GetMsgTime() uint32 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *InboundMessagePush) GetMsgKey() string {
	if x != nil {
		return x.MsgKey
	}
	return ""
}

func (x *InboundMessagePush) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *InboundMessagePush) GetMsgBody() []*MsgBodyElement {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *InboundMessagePush) GetCloudCustomData() string {
	if x != nil {
		return x.CloudCustomData
	}
	return ""
}

func (x *InboundMessagePush) GetEventTime() uint32 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *InboundMessagePush) GetBotOwnerId() string {
	if x != nil {
		return x.BotOwnerId
	}
	return ""
}

func (x *InboundMessagePush) GetRecallMsgSeqList() []*ImMsgSeq {
	if x != nil {
		return x.RecallMsgSeqList
	}
	return nil
}

func (x *InboundMessagePush) GetClawMsgType() EnumCLawMsgType {
	if x != nil {
		return x.ClawMsgType
	}
	return EnumCLawMsgType_CLAW_MSG_UNKNOWN
}

func (x *InboundMessagePush) GetPrivateFromGroupCode() string {
	if x != nil {
		return x.PrivateFromGroupCode
	}
	return ""
}

func (x *InboundMessagePush) GetLogExt() *LogInfoExt {
	if x != nil {
		return x.LogExt
	}
	return nil
}

type GetGroupMemberListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupCode     string                 `protobuf:"bytes,1,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListReq) Reset() {
	*x = GetGroupMemberListReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListReq) ProtoMessage() {}

func (x *GetGroupMemberListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListReq.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupMemberListReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	UserType      int32                  `protobuf:"varint,3,opt,name=userType,proto3" json:"userType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{11}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Member) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

type GetGroupMemberListRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MemberList    []*Member              `protobuf:"bytes,3,rep,name=memberList,proto3" json:"memberList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListRsp) Reset() {
	*x = GetGroupMemberListRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListRsp) ProtoMessage() {}

func (x *GetGroupMemberListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListRsp.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupMemberListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGroupMemberListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupMemberListRsp) GetMemberList() []*Member {
	if x != nil {
		return x.MemberList
	}
	return nil
}

type QueryGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupCode     string                 `protobuf:"bytes,1,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupInfoReq) Reset() {
	*x = QueryGroupInfoReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInfoReq) ProtoMessage() {}

func (x *QueryGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInfoReq.ProtoReflect.Descriptor instead.
func (*QueryGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{13}
}

func (x *QueryGroupInfoReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

type GroupInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GroupName          string                 `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	GroupOwnerUserId   string                 `protobuf:"bytes,2,opt,name=groupOwnerUserId,proto3" json:"groupOwnerUserId,omitempty"`
	GroupOwnerNickname string                 `protobuf:"bytes,3,opt,name=groupOwnerNickname,proto3" json:"groupOwnerNickname,omitempty"`
	GroupSize          int32                  `protobuf:"varint,4,opt,name=groupSize,proto3" json:"groupSize,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{14}
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetGroupOwnerUserId() string {
	if x != nil {
		return x.GroupOwnerUserId
	}
	return ""
}

func (x *GroupInfo) GetGroupOwnerNickname() string {
	if x != nil {
		return x.GroupOwnerNickname
	}
	return ""
}

func (x *GroupInfo) GetGroupSize() int32 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

type QueryGroupInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	GroupInfo     *GroupInfo             `protobuf:"bytes,3,opt,name=groupInfo,proto3" json:"groupInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupInfoRsp) Reset() {
	*x = QueryGroupInfoRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInfoRsp) ProtoMessage() {}

func (x *QueryGroupInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryGroupInfoRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{15}
}

func (x *QueryGroupInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryGroupInfoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryGroupInfoRsp) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type SendPrivateHeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	Heartbeat     EnumHeartbeat          `protobuf:"varint,3,opt,name=heartbeat,proto3,enum=trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeat" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateHeartbeatReq) Reset() {
	*x = SendPrivateHeartbeatReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateHeartbeatReq) ProtoMessage() {}

func (x *SendPrivateHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateHeartbeatReq.ProtoReflect.Descriptor instead.
func (*SendPrivateHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{16}
}

func (x *SendPrivateHeartbeatReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendPrivateHeartbeatReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendPrivateHeartbeatReq) GetHeartbeat() EnumHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return EnumHeartbeat_HEARTBEAT_UNKNOWN
}

type SendPrivateHeartbeatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateHeartbeatRsp) Reset() {
	*x = SendPrivateHeartbeatRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateHeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateHeartbeatRsp) ProtoMessage() {}

func (x *SendPrivateHeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateHeartbeatRsp.ProtoReflect.Descriptor instead.
func (*SendPrivateHeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{17}
}

func (x *SendPrivateHeartbeatRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendPrivateHeartbeatRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendGroupHeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	GroupCode     string                 `protobuf:"bytes,3,opt,name=groupCode,proto3" json:"groupCode,omitempty"`
	SendTime      int64                  `protobuf:"varint,4,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	Heartbeat     EnumHeartbeat          `protobuf:"varint,5,opt,name=heartbeat,proto3,enum=trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeat" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupHeartbeatReq) Reset() {
	*x = SendGroupHeartbeatReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupHeartbeatReq) ProtoMessage() {}

func (x *SendGroupHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupHeartbeatReq.ProtoReflect.Descriptor instead.
func (*SendGroupHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{18}
}

func (x *SendGroupHeartbeatReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

func (x *SendGroupHeartbeatReq) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendGroupHeartbeatReq) GetHeartbeat() EnumHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return EnumHeartbeat_HEARTBEAT_UNKNOWN
}

type SendGroupHeartbeatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupHeartbeatRsp) Reset() {
	*x = SendGroupHeartbeatRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupHeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupHeartbeatRsp) ProtoMessage() {}

func (x *SendGroupHeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupHeartbeatRsp.ProtoReflect.Descriptor instead.
func (*SendGroupHeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{19}
}

func (x *SendGroupHeartbeatRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupHeartbeatRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{20}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SyncCommandsData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BotCommands    []*Command             `protobuf:"bytes,1,rep,name=botCommands,proto3" json:"botCommands,omitempty"`
	PluginCommands []*Command             `protobuf:"bytes,2,rep,name=pluginCommands,proto3" json:"pluginCommands,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncCommandsData) Reset() {
	*x = SyncCommandsData{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommandsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommandsData) ProtoMessage() {}

func (x *SyncCommandsData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommandsData.ProtoReflect.Descriptor instead.
func (*SyncCommandsData) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{21}
}

func (x *SyncCommandsData) GetBotCommands() []*Command {
	if x != nil {
		return x.BotCommands
	}
	return nil
}

func (x *SyncCommandsData) GetPluginCommands() []*Command {
	if x != nil {
		return x.PluginCommands
	}
	return nil
}

type SyncInformationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncType      SyncInformationType    `protobuf:"varint,1,opt,name=syncType,proto3,enum=trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationType" json:"syncType,omitempty"`
	BotVersion    string                 `protobuf:"bytes,2,opt,name=botVersion,proto3" json:"botVersion,omitempty"`
	PluginVersion string                 `protobuf:"bytes,3,opt,name=pluginVersion,proto3" json:"pluginVersion,omitempty"`
	CommandData   *SyncCommandsData      `protobuf:"bytes,11,opt,name=commandData,proto3" json:"commandData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInformationReq) Reset() {
	*x = SyncInformationReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInformationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInformationReq) ProtoMessage() {}

func (x *SyncInformationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInformationReq.ProtoReflect.Descriptor instead.
func (*SyncInformationReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{22}
}

func (x *SyncInformationReq) GetSyncType() SyncInformationType {
	if x != nil {
		return x.SyncType
	}
	return SyncInformationType_SYNC_INFORMATION_TYPE_UNSPECIFIED
}

func (x *SyncInformationReq) GetBotVersion() string {
	if x != nil {
		return x.BotVersion
	}
	return ""
}

func (x *SyncInformationReq) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *SyncInformationReq) GetCommandData() *SyncCommandsData {
	if x != nil {
		return x.CommandData
	}
	return nil
}

type SyncInformationRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInformationRsp) Reset() {
	*x = SyncInformationRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInformationRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInformationRsp) ProtoMessage() {}

func (x *SyncInformationRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInformationRsp.ProtoReflect.Descriptor instead.
func (*SyncInformationRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP(), []int{23}
}

func (x *SyncInformationRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncInformationRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_channels_yuanbaobot_proto_biz_proto protoreflect.FileDescriptor

const file_pkg_channels_yuanbaobot_proto_biz_proto_rawDesc = "" +
	"\n" +
	"'pkg/channels/yuanbaobot/proto/biz.proto\x120trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy\x1a(pkg/channels/yuanbaobot/proto/conn.proto\"8\n" +
	"\bImMsgSeq\x12\x16\n" +
	"\x06msgSeq\x18\x01 \x01(\x04R\x06msgSeq\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\tR\x05msgId\"z\n" +
	"\x10ImImageInfoArray\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xf2\x02\n" +
	"\n" +
	"MsgContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12 \n" +
	"\vimageFormat\x18\x03 \x01(\rR\vimageFormat\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x12\x14\n" +
	"\x05sound\x18\a \x01(\tR\x05sound\x12j\n" +
	"\x0eimageInfoArray\x18\b \x03(\v2B.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImImageInfoArrayR\x0eimageInfoArray\x12\x14\n" +
	"\x05index\x18\t \x01(\rR\x05index\x12\x10\n" +
	"\x03url\x18\n" +
	" \x01(\tR\x03url\x12\x1a\n" +
	"\bfileSize\x18\v \x01(\rR\bfileSize\x12\x1a\n" +
	"\bfileName\x18\f \x01(\tR\bfileName\"\x88\x01\n" +
	"\x0eMsgBodyElement\x12\x18\n" +
	"\amsgType\x18\x01 \x01(\tR\amsgType\x12\\\n" +
	"\n" +
	"msgContent\x18\x02 \x01(\v2<.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgContentR\n" +
	"msgContent\"&\n" +
	"\n" +
	"LogInfoExt\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\"\xef\x02\n" +
	"\x11SendC2CMessageReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x12 \n" +
	"\vfromAccount\x18\x03 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\tmsgRandom\x18\x04 \x01(\rR\tmsgRandom\x12Z\n" +
	"\amsgBody\x18\x05 \x03(\v2@.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElementR\amsgBody\x12\x1c\n" +
	"\tgroupCode\x18\x06 \x01(\tR\tgroupCode\x12\x16\n" +
	"\x06msgSeq\x18\a \x01(\x04R\x06msgSeq\x12T\n" +
	"\x06logExt\x18\b \x01(\v2<.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExtR\x06logExt\"A\n" +
	"\x11SendC2CMessageRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x03\n" +
	"\x13SendGroupMessageReq\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\tgroupCode\x18\x02 \x01(\tR\tgroupCode\x12 \n" +
	"\vfromAccount\x18\x03 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x04 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06random\x18\x05 \x01(\tR\x06random\x12Z\n" +
	"\amsgBody\x18\x06 \x03(\v2@.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElementR\amsgBody\x12\x1a\n" +
	"\brefMsgId\x18\a \x01(\tR\brefMsgId\x12\x16\n" +
	"\x06msgSeq\x18\b \x01(\x04R\x06msgSeq\x12T\n" +
	"\x06logExt\x18\t \x01(\v2<.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExtR\x06logExt\"C\n" +
	"\x13SendGroupMessageRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\a\n" +
	"\x12InboundMessagePush\x12(\n" +
	"\x0fcallbackCommand\x18\x01 \x01(\tR\x0fcallbackCommand\x12 \n" +
	"\vfromAccount\x18\x02 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x03 \x01(\tR\ttoAccount\x12&\n" +
	"\x0esenderNickname\x18\x04 \x01(\tR\x0esenderNickname\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\tR\agroupId\x12\x1c\n" +
	"\tgroupCode\x18\x06 \x01(\tR\tgroupCode\x12\x1c\n" +
	"\tgroupName\x18\a \x01(\tR\tgroupName\x12\x16\n" +
	"\x06msgSeq\x18\b \x01(\rR\x06msgSeq\x12\x1c\n" +
	"\tmsgRandom\x18\t \x01(\rR\tmsgRandom\x12\x18\n" +
	"\amsgTime\x18\n" +
	" \x01(\rR\amsgTime\x12\x16\n" +
	"\x06msgKey\x18\v \x01(\tR\x06msgKey\x12\x14\n" +
	"\x05msgId\x18\f \x01(\tR\x05msgId\x12Z\n" +
	"\amsgBody\x18\r \x03(\v2@.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElementR\amsgBody\x12(\n" +
	"\x0fcloudCustomData\x18\x0e \x01(\tR\x0fcloudCustomData\x12\x1c\n" +
	"\teventTime\x18\x0f \x01(\rR\teventTime\x12\x1e\n" +
	"\n" +
	"botOwnerId\x18\x10 \x01(\tR\n" +
	"botOwnerId\x12f\n" +
	"\x10recallMsgSeqList\x18\x11 \x03(\v2:.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImMsgSeqR\x10recallMsgSeqList\x12c\n" +
	"\vclawMsgType\x18\x12 \x01(\x0e2A.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumCLawMsgTypeR\vclawMsgType\x122\n" +
	"\x14privateFromGroupCode\x18\x13 \x01(\tR\x14privateFromGroupCode\x12T\n" +
	"\x06logExt\x18\x14 \x01(\v2<.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExtR\x06logExt\"5\n" +
	"\x15GetGroupMemberListReq\x12\x1c\n" +
	"\tgroupCode\x18\x01 \x01(\tR\tgroupCode\"X\n" +
	"\x06Member\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1a\n" +
	"\buserType\x18\x03 \x01(\x05R\buserType\"\x9f\x01\n" +
	"\x15GetGroupMemberListRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12X\n" +
	"\n" +
	"memberList\x18\x03 \x03(\v28.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MemberR\n" +
	"memberList\"1\n" +
	"\x11QueryGroupInfoReq\x12\x1c\n" +
	"\tgroupCode\x18\x01 \x01(\tR\tgroupCode\"\xa3\x01\n" +
	"\tGroupInfo\x12\x1c\n" +
	"\tgroupName\x18\x01 \x01(\tR\tgroupName\x12*\n" +
	"\x10groupOwnerUserId\x18\x02 \x01(\tR\x10groupOwnerUserId\x12.\n" +
	"\x12groupOwnerNickname\x18\x03 \x01(\tR\x12groupOwnerNickname\x12\x1c\n" +
	"\tgroupSize\x18\x04 \x01(\x05R\tgroupSize\"\x94\x01\n" +
	"\x11QueryGroupInfoRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12Y\n" +
	"\tgroupInfo\x18\x03 \x01(\v2;.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GroupInfoR\tgroupInfo\"\xb8\x01\n" +
	"\x17SendPrivateHeartbeatReq\x12 \n" +
	"\vfromAccount\x18\x01 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x12]\n" +
	"\theartbeat\x18\x03 \x01(\x0e2?.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeatR\theartbeat\"?\n" +
	"\x17SendPrivateHeartbeatRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xf0\x01\n" +
	"\x15SendGroupHeartbeatReq\x12 \n" +
	"\vfromAccount\x18\x01 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x02 \x01(\tR\ttoAccount\x12\x1c\n" +
	"\tgroupCode\x18\x03 \x01(\tR\tgroupCode\x12\x1a\n" +
	"\bsendTime\x18\x04 \x01(\x03R\bsendTime\x12]\n" +
	"\theartbeat\x18\x05 \x01(\x0e2?.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeatR\theartbeat\"=\n" +
	"\x15SendGroupHeartbeatRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"?\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xd2\x01\n" +
	"\x10SyncCommandsData\x12[\n" +
	"\vbotCommands\x18\x01 \x03(\v29.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.CommandR\vbotCommands\x12a\n" +
	"\x0epluginCommands\x18\x02 \x03(\v29.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.CommandR\x0epluginCommands\"\xa3\x02\n" +
	"\x12SyncInformationReq\x12a\n" +
	"\bsyncType\x18\x01 \x01(\x0e2E.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationTypeR\bsyncType\x12\x1e\n" +
	"\n" +
	"botVersion\x18\x02 \x01(\tR\n" +
	"botVersion\x12$\n" +
	"\rpluginVersion\x18\x03 \x01(\tR\rpluginVersion\x12d\n" +
	"\vcommandData\x18\v \x01(\v2B.trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncCommandsDataR\vcommandData\":\n" +
	"\x12SyncInformationRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*Q\n" +
	"\x0fEnumCLawMsgType\x12\x14\n" +
	"\x10CLAW_MSG_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eCLAW_MSG_GROUP\x10\x01\x12\x14\n" +
	"\x10CLAW_MSG_PRIVATE\x10\x02*S\n" +
	"\rEnumHeartbeat\x12\x15\n" +
	"\x11HEARTBEAT_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11HEARTBEAT_RUNNING\x10\x01\x12\x14\n" +
	"\x10HEARTBEAT_FINISH\x10\x02*`\n" +
	"\x13SyncInformationType\x12%\n" +
	"!SYNC_INFORMATION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSYNC_INFORMATION_TYPE_COMMANDS\x10\x01B5Z3github.com/yhlooo/nfa/pkg/channels/yuanbaobot/protob\x06proto3"

var (
	file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescOnce sync.Once
	file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescData []byte
)

func file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescGZIP() []byte {
	file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescOnce.Do(func() {
		file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_channels_yuanbaobot_proto_biz_proto_rawDesc), len(file_pkg_channels_yuanbaobot_proto_biz_proto_rawDesc)))
	})
	return file_pkg_channels_yuanbaobot_proto_biz_proto_rawDescData
}

var file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_channels_yuanbaobot_proto_biz_proto_goTypes = []any{
	(EnumCLawMsgType)(0),            // 0: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumCLawMsgType
	(EnumHeartbeat)(0),              // 1: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeat
	(SyncInformationType)(0),        // 2: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationType
	(*ImMsgSeq)(nil),                // 3: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImMsgSeq
	(*ImImageInfoArray)(nil),        // 4: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImImageInfoArray
	(*MsgContent)(nil),              // 5: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgContent
	(*MsgBodyElement)(nil),          // 6: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElement
	(*LogInfoExt)(nil),              // 7: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExt
	(*SendC2CMessageReq)(nil),       // 8: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendC2CMessageReq
	(*SendC2CMessageRsp)(nil),       // 9: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendC2CMessageRsp
	(*SendGroupMessageReq)(nil),     // 10: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupMessageReq
	(*SendGroupMessageRsp)(nil),     // 11: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupMessageRsp
	(*InboundMessagePush)(nil),      // 12: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.InboundMessagePush
	(*GetGroupMemberListReq)(nil),   // 13: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GetGroupMemberListReq
	(*Member)(nil),                  // 14: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.Member
	(*GetGroupMemberListRsp)(nil),   // 15: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GetGroupMemberListRsp
	(*QueryGroupInfoReq)(nil),       // 16: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.QueryGroupInfoReq
	(*GroupInfo)(nil),               // 17: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GroupInfo
	(*QueryGroupInfoRsp)(nil),       // 18: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.QueryGroupInfoRsp
	(*SendPrivateHeartbeatReq)(nil), // 19: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendPrivateHeartbeatReq
	(*SendPrivateHeartbeatRsp)(nil), // 20: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendPrivateHeartbeatRsp
	(*SendGroupHeartbeatReq)(nil),   // 21: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupHeartbeatReq
	(*SendGroupHeartbeatRsp)(nil),   // 22: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupHeartbeatRsp
	(*Command)(nil),                 // 23: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.Command
	(*SyncCommandsData)(nil),        // 24: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncCommandsData
	(*SyncInformationReq)(nil),      // 25: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationReq
	(*SyncInformationRsp)(nil),      // 26: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationRsp
}
var file_pkg_channels_yuanbaobot_proto_biz_proto_depIdxs = []int32{
	4,  // 0: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgContent.imageInfoArray:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImImageInfoArray
	5,  // 1: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElement.msgContent:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgContent
	6,  // 2: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendC2CMessageReq.msgBody:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElement
	7,  // 3: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendC2CMessageReq.logExt:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExt
	6,  // 4: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupMessageReq.msgBody:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElement
	7,  // 5: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupMessageReq.logExt:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExt
	6,  // 6: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.InboundMessagePush.msgBody:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.MsgBodyElement
	3,  // 7: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.InboundMessagePush.recallMsgSeqList:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.ImMsgSeq
	0,  // 8: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.InboundMessagePush.clawMsgType:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumCLawMsgType
	7,  // 9: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.InboundMessagePush.logExt:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.LogInfoExt
	14, // 10: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GetGroupMemberListRsp.memberList:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.Member
	17, // 11: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.QueryGroupInfoRsp.groupInfo:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.GroupInfo
	1,  // 12: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendPrivateHeartbeatReq.heartbeat:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeat
	1,  // 13: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SendGroupHeartbeatReq.heartbeat:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.EnumHeartbeat
	23, // 14: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncCommandsData.botCommands:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.Command
	23, // 15: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncCommandsData.pluginCommands:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.Command
	2,  // 16: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationReq.syncType:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationType
	24, // 17: trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncInformationReq.commandData:type_name -> trpc.yuanbao.yuanbao_conn.yuanbao_openclaw_proxy.SyncCommandsData
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_channels_yuanbaobot_proto_biz_proto_init() }
func file_pkg_channels_yuanbaobot_proto_biz_proto_init() {
	if File_pkg_channels_yuanbaobot_proto_biz_proto != nil {
		return
	}
	file_pkg_channels_yuanbaobot_proto_conn_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_channels_yuanbaobot_proto_biz_proto_rawDesc), len(file_pkg_channels_yuanbaobot_proto_biz_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_channels_yuanbaobot_proto_biz_proto_goTypes,
		DependencyIndexes: file_pkg_channels_yuanbaobot_proto_biz_proto_depIdxs,
		EnumInfos:         file_pkg_channels_yuanbaobot_proto_biz_proto_enumTypes,
		MessageInfos:      file_pkg_channels_yuanbaobot_proto_biz_proto_msgTypes,
	}.Build()
	File_pkg_channels_yuanbaobot_proto_biz_proto = out.File
	file_pkg_channels_yuanbaobot_proto_biz_proto_goTypes = nil
	file_pkg_channels_yuanbaobot_proto_biz_proto_depIdxs = nil
}
