// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/channels/yuanbaobot/proto/conn.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetCode int32

const (
	RetCode_SUCCESS                      RetCode = 0
	RetCode_PARAMS_INVALID               RetCode = 40011
	RetCode_AUTH_FAIL                    RetCode = 40100
	RetCode_UNKNOWN_ROUTE                RetCode = 40300
	RetCode_ALREADY_AUTH                 RetCode = 41101
	RetCode_SAME_KIND_DEV_LOGIN          RetCode = 41102
	RetCode_AUTH_TOKEN_INVALID           RetCode = 41103
	RetCode_AUTH_TOKEN_EXPIRED           RetCode = 41104
	RetCode_AUTH_USER_NOT_REGISTERED     RetCode = 41105
	RetCode_AUTH_USER_FORBIDDEN          RetCode = 41106
	RetCode_AUTH_USER_UNQUALIFIED        RetCode = 41107
	RetCode_AUTH_TOKEN_FORCED_EXPIRATION RetCode = 41108
	RetCode_PROHIBIT_APP_VERSION         RetCode = 41109
	RetCode_PACKAGE_SIGN_ILLEGAL         RetCode = 41110
	RetCode_INNER_SVR_FAIL               RetCode = 50400
	RetCode_OVERLOAD_CONTROL             RetCode = 50503
	RetCode_SET_STATE_CONFLICT           RetCode = 51001
	RetCode_CONN_OVER_LIMIT              RetCode = 51002
	RetCode_NO_USER_ONLINE               RetCode = 51003
	RetCode_PARTIAL_FAIL                 RetCode = 51004
	RetCode_NET_FAIL                     RetCode = 90001
	RetCode_BACKEND_RETURN_FAIL          RetCode = 90003
	RetCode_USER_OFFLINE                 RetCode = 20001
	RetCode_USER_NOT_EXIST               RetCode = 20002
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:     "SUCCESS",
		40011: "PARAMS_INVALID",
		40100: "AUTH_FAIL",
		40300: "UNKNOWN_ROUTE",
		41101: "ALREADY_AUTH",
		41102: "SAME_KIND_DEV_LOGIN",
		41103: "AUTH_TOKEN_INVALID",
		41104: "AUTH_TOKEN_EXPIRED",
		41105: "AUTH_USER_NOT_REGISTERED",
		41106: "AUTH_USER_FORBIDDEN",
		41107: "AUTH_USER_UNQUALIFIED",
		41108: "AUTH_TOKEN_FORCED_EXPIRATION",
		41109: "PROHIBIT_APP_VERSION",
		41110: "PACKAGE_SIGN_ILLEGAL",
		50400: "INNER_SVR_FAIL",
		50503: "OVERLOAD_CONTROL",
		51001: "SET_STATE_CONFLICT",
		51002: "CONN_OVER_LIMIT",
		51003: "NO_USER_ONLINE",
		51004: "PARTIAL_FAIL",
		90001: "NET_FAIL",
		90003: "BACKEND_RETURN_FAIL",
		20001: "USER_OFFLINE",
		20002: "USER_NOT_EXIST",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":                      0,
		"PARAMS_INVALID":               40011,
		"AUTH_FAIL":                    40100,
		"UNKNOWN_ROUTE":                40300,
		"ALREADY_AUTH":                 41101,
		"SAME_KIND_DEV_LOGIN":          41102,
		"AUTH_TOKEN_INVALID":           41103,
		"AUTH_TOKEN_EXPIRED":           41104,
		"AUTH_USER_NOT_REGISTERED":     41105,
		"AUTH_USER_FORBIDDEN":          41106,
		"AUTH_USER_UNQUALIFIED":        41107,
		"AUTH_TOKEN_FORCED_EXPIRATION": 41108,
		"PROHIBIT_APP_VERSION":         41109,
		"PACKAGE_SIGN_ILLEGAL":         41110,
		"INNER_SVR_FAIL":               50400,
		"OVERLOAD_CONTROL":             50503,
		"SET_STATE_CONFLICT":           51001,
		"CONN_OVER_LIMIT":              51002,
		"NO_USER_ONLINE":               51003,
		"PARTIAL_FAIL":                 51004,
		"NET_FAIL":                     90001,
		"BACKEND_RETURN_FAIL":          90003,
		"USER_OFFLINE":                 20001,
		"USER_NOT_EXIST":               20002,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_pkg_channels_yuanbaobot_proto_conn_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{0}
}

type HeadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadMeta) Reset() {
	*x = HeadMeta{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadMeta) ProtoMessage() {}

func (x *HeadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadMeta.ProtoReflect.Descriptor instead.
func (*HeadMeta) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{0}
}

func (x *HeadMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeadMeta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdType       uint32                 `protobuf:"varint,1,opt,name=cmdType,proto3" json:"cmdType,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	SeqNo         uint32                 `protobuf:"varint,3,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
	MsgId         string                 `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Module        string                 `protobuf:"bytes,5,opt,name=module,proto3" json:"module,omitempty"`
	NeedAck       bool                   `protobuf:"varint,6,opt,name=needAck,proto3" json:"needAck,omitempty"`
	Meta          []*HeadMeta            `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{1}
}

func (x *Head) GetCmdType() uint32 {
	if x != nil {
		return x.CmdType
	}
	return 0
}

func (x *Head) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Head) GetSeqNo() uint32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *Head) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Head) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Head) GetNeedAck() bool {
	if x != nil {
		return x.NeedAck
	}
	return false
}

func (x *Head) GetMeta() []*HeadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Head) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ConnMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *Head                  `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnMsg) Reset() {
	*x = ConnMsg{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMsg) ProtoMessage() {}

func (x *ConnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMsg.ProtoReflect.Descriptor instead.
func (*ConnMsg) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{2}
}

func (x *ConnMsg) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *ConnMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DirectedPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectedPush) Reset() {
	*x = DirectedPush{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectedPush) ProtoMessage() {}

func (x *DirectedPush) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectedPush.ProtoReflect.Descriptor instead.
func (*DirectedPush) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{3}
}

func (x *DirectedPush) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DirectedPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{4}
}

func (x *AuthInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AuthInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuthInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeviceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppVersion         string                 `protobuf:"bytes,1,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	AppOperationSystem string                 `protobuf:"bytes,2,opt,name=appOperationSystem,proto3" json:"appOperationSystem,omitempty"`
	AppBundleId        string                 `protobuf:"bytes,3,opt,name=appBundleId,proto3" json:"appBundleId,omitempty"`
	Qimei              string                 `protobuf:"bytes,4,opt,name=qimei,proto3" json:"qimei,omitempty"`
	Qimei36            string                 `protobuf:"bytes,5,opt,name=qimei36,proto3" json:"qimei36,omitempty"`
	H38                string                 `protobuf:"bytes,6,opt,name=h38,proto3" json:"h38,omitempty"`
	Language           string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	DeviceId           string                 `protobuf:"bytes,8,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceName         string                 `protobuf:"bytes,9,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	InstanceId         string                 `protobuf:"bytes,10,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Tid                string                 `protobuf:"bytes,11,opt,name=tid,proto3" json:"tid,omitempty"`
	Uskey              string                 `protobuf:"bytes,12,opt,name=uskey,proto3" json:"uskey,omitempty"`
	BusParamsMd5       string                 `protobuf:"bytes,13,opt,name=busParamsMd5,proto3" json:"busParamsMd5,omitempty"`
	PackageType        string                 `protobuf:"bytes,14,opt,name=packageType,proto3" json:"packageType,omitempty"`
	AppPublishChannel  string                 `protobuf:"bytes,15,opt,name=appPublishChannel,proto3" json:"appPublishChannel,omitempty"`
	SignVersion        string                 `protobuf:"bytes,16,opt,name=signVersion,proto3" json:"signVersion,omitempty"`
	PackageSignature   string                 `protobuf:"bytes,17,opt,name=packageSignature,proto3" json:"packageSignature,omitempty"`
	Brand              string                 `protobuf:"bytes,18,opt,name=brand,proto3" json:"brand,omitempty"`
	H42                string                 `protobuf:"bytes,19,opt,name=h42,proto3" json:"h42,omitempty"`
	XDeviceId          string                 `protobuf:"bytes,20,opt,name=xDeviceId,proto3" json:"xDeviceId,omitempty"`
	XPlatform          string                 `protobuf:"bytes,21,opt,name=xPlatform,proto3" json:"xPlatform,omitempty"`
	DialToken          string                 `protobuf:"bytes,22,opt,name=dialToken,proto3" json:"dialToken,omitempty"`
	Qimei36Token       string                 `protobuf:"bytes,23,opt,name=qimei36Token,proto3" json:"qimei36Token,omitempty"`
	BotVersion         string                 `protobuf:"bytes,24,opt,name=botVersion,proto3" json:"botVersion,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetAppOperationSystem() string {
	if x != nil {
		return x.AppOperationSystem
	}
	return ""
}

func (x *DeviceInfo) GetAppBundleId() string {
	if x != nil {
		return x.AppBundleId
	}
	return ""
}

func (x *DeviceInfo) GetQimei() string {
	if x != nil {
		return x.Qimei
	}
	return ""
}

func (x *DeviceInfo) GetQimei36() string {
	if x != nil {
		return x.Qimei36
	}
	return ""
}

func (x *DeviceInfo) GetH38() string {
	if x != nil {
		return x.H38
	}
	return ""
}

func (x *DeviceInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeviceInfo) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *DeviceInfo) GetUskey() string {
	if x != nil {
		return x.Uskey
	}
	return ""
}

func (x *DeviceInfo) GetBusParamsMd5() string {
	if x != nil {
		return x.BusParamsMd5
	}
	return ""
}

func (x *DeviceInfo) GetPackageType() string {
	if x != nil {
		return x.PackageType
	}
	return ""
}

func (x *DeviceInfo) GetAppPublishChannel() string {
	if x != nil {
		return x.AppPublishChannel
	}
	return ""
}

func (x *DeviceInfo) GetSignVersion() string {
	if x != nil {
		return x.SignVersion
	}
	return ""
}

func (x *DeviceInfo) GetPackageSignature() string {
	if x != nil {
		return x.PackageSignature
	}
	return ""
}

func (x *DeviceInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceInfo) GetH42() string {
	if x != nil {
		return x.H42
	}
	return ""
}

func (x *DeviceInfo) GetXDeviceId() string {
	if x != nil {
		return x.XDeviceId
	}
	return ""
}

func (x *DeviceInfo) GetXPlatform() string {
	if x != nil {
		return x.XPlatform
	}
	return ""
}

func (x *DeviceInfo) GetDialToken() string {
	if x != nil {
		return x.DialToken
	}
	return ""
}

func (x *DeviceInfo) GetQimei36Token() string {
	if x != nil {
		return x.Qimei36Token
	}
	return ""
}

func (x *DeviceInfo) GetBotVersion() string {
	if x != nil {
		return x.BotVersion
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	UniqueKey     string                 `protobuf:"bytes,2,opt,name=uniqueKey,proto3" json:"uniqueKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Container) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

type AuthBindReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	AuthInfo      *AuthInfo              `protobuf:"bytes,2,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,3,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	ContainerInfo *Container             `protobuf:"bytes,4,opt,name=containerInfo,proto3" json:"containerInfo,omitempty"`
	EnvName       string                 `protobuf:"bytes,5,opt,name=envName,proto3" json:"envName,omitempty"`
	BindMode      uint32                 `protobuf:"varint,6,opt,name=bindMode,proto3" json:"bindMode,omitempty"`
	ForceToken    string                 `protobuf:"bytes,7,opt,name=forceToken,proto3" json:"forceToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthBindReq) Reset() {
	*x = AuthBindReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindReq) ProtoMessage() {}

func (x *AuthBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindReq.ProtoReflect.Descriptor instead.
func (*AuthBindReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{7}
}

func (x *AuthBindReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AuthBindReq) GetAuthInfo() *AuthInfo {
	if x != nil {
		return x.AuthInfo
	}
	return nil
}

func (x *AuthBindReq) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *AuthBindReq) GetContainerInfo() *Container {
	if x != nil {
		return x.ContainerInfo
	}
	return nil
}

func (x *AuthBindReq) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *AuthBindReq) GetBindMode() uint32 {
	if x != nil {
		return x.BindMode
	}
	return 0
}

func (x *AuthBindReq) GetForceToken() string {
	if x != nil {
		return x.ForceToken
	}
	return ""
}

type AuthBindRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConnectId     string                 `protobuf:"bytes,3,opt,name=connectId,proto3" json:"connectId,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthBindRsp) Reset() {
	*x = AuthBindRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindRsp) ProtoMessage() {}

func (x *AuthBindRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBindRsp.ProtoReflect.Descriptor instead.
func (*AuthBindRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{8}
}

func (x *AuthBindRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthBindRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthBindRsp) GetConnectId() string {
	if x != nil {
		return x.ConnectId
	}
	return ""
}

func (x *AuthBindRsp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthBindRsp) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{9}
}

type PingRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeartInterval uint32                 `protobuf:"varint,1,opt,name=heartInterval,proto3" json:"heartInterval,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRsp) Reset() {
	*x = PingRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRsp) ProtoMessage() {}

func (x *PingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRsp.ProtoReflect.Descriptor instead.
func (*PingRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{10}
}

func (x *PingRsp) GetHeartInterval() uint32 {
	if x != nil {
		return x.HeartInterval
	}
	return 0
}

func (x *PingRsp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type KickoutMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	OtherDeviceName string                 `protobuf:"bytes,3,opt,name=otherDeviceName,proto3" json:"otherDeviceName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KickoutMsg) Reset() {
	*x = KickoutMsg{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickoutMsg) ProtoMessage() {}

func (x *KickoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickoutMsg.ProtoReflect.Descriptor instead.
func (*KickoutMsg) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{11}
}

func (x *KickoutMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *KickoutMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickoutMsg) GetOtherDeviceName() string {
	if x != nil {
		return x.OtherDeviceName
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{12}
}

func (x *Meta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Meta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateMetaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetaInfos     []*Meta                `protobuf:"bytes,1,rep,name=metaInfos,proto3" json:"metaInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaReq) Reset() {
	*x = UpdateMetaReq{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaReq) ProtoMessage() {}

func (x *UpdateMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaReq.ProtoReflect.Descriptor instead.
func (*UpdateMetaReq) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMetaReq) GetMetaInfos() []*Meta {
	if x != nil {
		return x.MetaInfos
	}
	return nil
}

type UpdateMetaRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaRsp) Reset() {
	*x = UpdateMetaRsp{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaRsp) ProtoMessage() {}

func (x *UpdateMetaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaRsp.ProtoReflect.Descriptor instead.
func (*UpdateMetaRsp) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMetaRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateMetaRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PushMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsg) Reset() {
	*x = PushMsg{}
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsg) ProtoMessage() {}

func (x *PushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsg.ProtoReflect.Descriptor instead.
func (*PushMsg) Descriptor() ([]byte, []int) {
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP(), []int{15}
}

func (x *PushMsg) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *PushMsg) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PushMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PushMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_channels_yuanbaobot_proto_conn_proto protoreflect.FileDescriptor

const file_pkg_channels_yuanbaobot_proto_conn_proto_rawDesc = "" +
	"\n" +
	"(pkg/channels/yuanbaobot/proto/conn.proto\x12\x18trpc.yuanbao.conn_common\"2\n" +
	"\bHeadMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe0\x01\n" +
	"\x04Head\x12\x18\n" +
	"\acmdType\x18\x01 \x01(\rR\acmdType\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05seqNo\x18\x03 \x01(\rR\x05seqNo\x12\x14\n" +
	"\x05msgId\x18\x04 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06module\x18\x05 \x01(\tR\x06module\x12\x18\n" +
	"\aneedAck\x18\x06 \x01(\bR\aneedAck\x126\n" +
	"\x04meta\x18\a \x03(\v2\".trpc.yuanbao.conn_common.HeadMetaR\x04meta\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"Q\n" +
	"\aConnMsg\x122\n" +
	"\x04head\x18\x01 \x01(\v2\x1e.trpc.yuanbao.conn_common.HeadR\x04head\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"<\n" +
	"\fDirectedPush\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"J\n" +
	"\bAuthInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xe8\x05\n" +
	"\n" +
	"DeviceInfo\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x01 \x01(\tR\n" +
	"appVersion\x12.\n" +
	"\x12appOperationSystem\x18\x02 \x01(\tR\x12appOperationSystem\x12 \n" +
	"\vappBundleId\x18\x03 \x01(\tR\vappBundleId\x12\x14\n" +
	"\x05qimei\x18\x04 \x01(\tR\x05qimei\x12\x18\n" +
	"\aqimei36\x18\x05 \x01(\tR\aqimei36\x12\x10\n" +
	"\x03h38\x18\x06 \x01(\tR\x03h38\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1a\n" +
	"\bdeviceId\x18\b \x01(\tR\bdeviceId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\t \x01(\tR\n" +
	"deviceName\x12\x1e\n" +
	"\n" +
	"instanceId\x18\n" +
	" \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03tid\x18\v \x01(\tR\x03tid\x12\x14\n" +
	"\x05uskey\x18\f \x01(\tR\x05uskey\x12\"\n" +
	"\fbusParamsMd5\x18\r \x01(\tR\fbusParamsMd5\x12 \n" +
	"\vpackageType\x18\x0e \x01(\tR\vpackageType\x12,\n" +
	"\x11appPublishChannel\x18\x0f \x01(\tR\x11appPublishChannel\x12 \n" +
	"\vsignVersion\x18\x10 \x01(\tR\vsignVersion\x12*\n" +
	"\x10packageSignature\x18\x11 \x01(\tR\x10packageSignature\x12\x14\n" +
	"\x05brand\x18\x12 \x01(\tR\x05brand\x12\x10\n" +
	"\x03h42\x18\x13 \x01(\tR\x03h42\x12\x1c\n" +
	"\txDeviceId\x18\x14 \x01(\tR\txDeviceId\x12\x1c\n" +
	"\txPlatform\x18\x15 \x01(\tR\txPlatform\x12\x1c\n" +
	"\tdialToken\x18\x16 \x01(\tR\tdialToken\x12\"\n" +
	"\fqimei36Token\x18\x17 \x01(\tR\fqimei36Token\x12\x1e\n" +
	"\n" +
	"botVersion\x18\x18 \x01(\tR\n" +
	"botVersion\"=\n" +
	"\tContainer\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1c\n" +
	"\tuniqueKey\x18\x02 \x01(\tR\tuniqueKey\"\xca\x02\n" +
	"\vAuthBindReq\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12>\n" +
	"\bauthInfo\x18\x02 \x01(\v2\".trpc.yuanbao.conn_common.AuthInfoR\bauthInfo\x12D\n" +
	"\n" +
	"deviceInfo\x18\x03 \x01(\v2$.trpc.yuanbao.conn_common.DeviceInfoR\n" +
	"deviceInfo\x12I\n" +
	"\rcontainerInfo\x18\x04 \x01(\v2#.trpc.yuanbao.conn_common.ContainerR\rcontainerInfo\x12\x18\n" +
	"\aenvName\x18\x05 \x01(\tR\aenvName\x12\x1a\n" +
	"\bbindMode\x18\x06 \x01(\rR\bbindMode\x12\x1e\n" +
	"\n" +
	"forceToken\x18\a \x01(\tR\n" +
	"forceToken\"\x93\x01\n" +
	"\vAuthBindRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tconnectId\x18\x03 \x01(\tR\tconnectId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bclientIp\x18\x05 \x01(\tR\bclientIp\"\t\n" +
	"\aPingReq\"M\n" +
	"\aPingRsp\x12$\n" +
	"\rheartInterval\x18\x01 \x01(\rR\rheartInterval\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"f\n" +
	"\n" +
	"KickoutMsg\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12(\n" +
	"\x0fotherDeviceName\x18\x03 \x01(\tR\x0fotherDeviceName\".\n" +
	"\x04Meta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"M\n" +
	"\rUpdateMetaReq\x12<\n" +
	"\tmetaInfos\x18\x01 \x03(\v2\x1e.trpc.yuanbao.conn_common.MetaR\tmetaInfos\"=\n" +
	"\rUpdateMetaRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\aPushMsg\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\tR\x05msgId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data*\xc7\x04\n" +
	"\aRetCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x14\n" +
	"\x0ePARAMS_INVALID\x10˸\x02\x12\x0f\n" +
	"\tAUTH_FAIL\x10\xa4\xb9\x02\x12\x13\n" +
	"\rUNKNOWN_ROUTE\x10\xec\xba\x02\x12\x12\n" +
	"\fALREADY_AUTH\x10\x8d\xc1\x02\x12\x19\n" +
	"\x13SAME_KIND_DEV_LOGIN\x10\x8e\xc1\x02\x12\x18\n" +
	"\x12AUTH_TOKEN_INVALID\x10\x8f\xc1\x02\x12\x18\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\x90\xc1\x02\x12\x1e\n" +
	"\x18AUTH_USER_NOT_REGISTERED\x10\x91\xc1\x02\x12\x19\n" +
	"\x13AUTH_USER_FORBIDDEN\x10\x92\xc1\x02\x12\x1b\n" +
	"\x15AUTH_USER_UNQUALIFIED\x10\x93\xc1\x02\x12\"\n" +
	"\x1cAUTH_TOKEN_FORCED_EXPIRATION\x10\x94\xc1\x02\x12\x1a\n" +
	"\x14PROHIBIT_APP_VERSION\x10\x95\xc1\x02\x12\x1a\n" +
	"\x14PACKAGE_SIGN_ILLEGAL\x10\x96\xc1\x02\x12\x14\n" +
	"\x0eINNER_SVR_FAIL\x10\xe0\x89\x03\x12\x16\n" +
	"\x10OVERLOAD_CONTROL\x10Ǌ\x03\x12\x18\n" +
	"\x12SET_STATE_CONFLICT\x10\xb9\x8e\x03\x12\x15\n" +
	"\x0fCONN_OVER_LIMIT\x10\xba\x8e\x03\x12\x14\n" +
	"\x0eNO_USER_ONLINE\x10\xbb\x8e\x03\x12\x12\n" +
	"\fPARTIAL_FAIL\x10\xbc\x8e\x03\x12\x0e\n" +
	"\bNET_FAIL\x10\x91\xbf\x05\x12\x19\n" +
	"\x13BACKEND_RETURN_FAIL\x10\x93\xbf\x05\x12\x12\n" +
	"\fUSER_OFFLINE\x10\xa1\x9c\x01\x12\x14\n" +
	"\x0eUSER_NOT_EXIST\x10\xa2\x9c\x01B5Z3github.com/yhlooo/nfa/pkg/channels/yuanbaobot/protob\x06proto3"

var (
	file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescOnce sync.Once
	file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescData []byte
)

func file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescGZIP() []byte {
	file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescOnce.Do(func() {
		file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_channels_yuanbaobot_proto_conn_proto_rawDesc), len(file_pkg_channels_yuanbaobot_proto_conn_proto_rawDesc)))
	})
	return file_pkg_channels_yuanbaobot_proto_conn_proto_rawDescData
}

var file_pkg_channels_yuanbaobot_proto_conn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_channels_yuanbaobot_proto_conn_proto_goTypes = []any{
	(RetCode)(0),          // 0: trpc.yuanbao.conn_common.RetCode
	(*HeadMeta)(nil),      // 1: trpc.yuanbao.conn_common.HeadMeta
	(*Head)(nil),          // 2: trpc.yuanbao.conn_common.Head
	(*ConnMsg)(nil),       // 3: trpc.yuanbao.conn_common.ConnMsg
	(*DirectedPush)(nil),  // 4: trpc.yuanbao.conn_common.DirectedPush
	(*AuthInfo)(nil),      // 5: trpc.yuanbao.conn_common.AuthInfo
	(*DeviceInfo)(nil),    // 6: trpc.yuanbao.conn_common.DeviceInfo
	(*Container)(nil),     // 7: trpc.yuanbao.conn_common.Container
	(*AuthBindReq)(nil),   // 8: trpc.yuanbao.conn_common.AuthBindReq
	(*AuthBindRsp)(nil),   // 9: trpc.yuanbao.conn_common.AuthBindRsp
	(*PingReq)(nil),       // 10: trpc.yuanbao.conn_common.PingReq
	(*PingRsp)(nil),       // 11: trpc.yuanbao.conn_common.PingRsp
	(*KickoutMsg)(nil),    // 12: trpc.yuanbao.conn_common.KickoutMsg
	(*Meta)(nil),          // 13: trpc.yuanbao.conn_common.Meta
	(*UpdateMetaReq)(nil), // 14: trpc.yuanbao.conn_common.UpdateMetaReq
	(*UpdateMetaRsp)(nil), // 15: trpc.yuanbao.conn_common.UpdateMetaRsp
	(*PushMsg)(nil),       // 16: trpc.yuanbao.conn_common.PushMsg
}
var file_pkg_channels_yuanbaobot_proto_conn_proto_depIdxs = []int32{
	1,  // 0: trpc.yuanbao.conn_common.Head.meta:type_name -> trpc.yuanbao.conn_common.HeadMeta
	2,  // 1: trpc.yuanbao.conn_common.ConnMsg.head:type_name -> trpc.yuanbao.conn_common.Head
	5,  // 2: trpc.yuanbao.conn_common.AuthBindReq.authInfo:type_name -> trpc.yuanbao.conn_common.AuthInfo
	6,  // 3: trpc.yuanbao.conn_common.AuthBindReq.deviceInfo:type_name -> trpc.yuanbao.conn_common.DeviceInfo
	7,  // 4: trpc.yuanbao.conn_common.AuthBindReq.containerInfo:type_name -> trpc.yuanbao.conn_common.Container
	13, // 5: trpc.yuanbao.conn_common.UpdateMetaReq.metaInfos:type_name -> trpc.yuanbao.conn_common.Meta
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_channels_yuanbaobot_proto_conn_proto_init() }
func file_pkg_channels_yuanbaobot_proto_conn_proto_init() {
	if File_pkg_channels_yuanbaobot_proto_conn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_channels_yuanbaobot_proto_conn_proto_rawDesc), len(file_pkg_channels_yuanbaobot_proto_conn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_channels_yuanbaobot_proto_conn_proto_goTypes,
		DependencyIndexes: file_pkg_channels_yuanbaobot_proto_conn_proto_depIdxs,
		EnumInfos:         file_pkg_channels_yuanbaobot_proto_conn_proto_enumTypes,
		MessageInfos:      file_pkg_channels_yuanbaobot_proto_conn_proto_msgTypes,
	}.Build()
	File_pkg_channels_yuanbaobot_proto_conn_proto = out.File
	file_pkg_channels_yuanbaobot_proto_conn_proto_goTypes = nil
	file_pkg_channels_yuanbaobot_proto_conn_proto_depIdxs = nil
}
